project:
  type: website
  output-dir: docs

website:
  favicon: about/dna_logo.svg
  title: "Emilio Egal"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Research projects
      - href: CV.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - about.qmd
  page-footer:
    left: "Copyright 2026, Emilio Egal"
    right:
      - icon: github
        href: https://github.com/EmilioEgal

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
